### PR TITLE
Add recursiveness with fixed circular imports and correct order of files

### PR DESCRIPTION
**Pull request by dhardtke**
See #102 and #109

### CODE REVIEW

**Comment by dhardtke** [comment]
I will fix the build when I have time for that

**Comment by dhardtke** [comment]
See #2

**Comment by dhardtke** [comment]
I think Codesleeve\Sprockets\ManifestTest::testFileLoadingOrderForRequireTree can't work because data-changer.js and data-colors.js.coffee are in the same folder so RequireTreeDf has no effect right now

**Comment by kdocki** [comment]
After doing some research on this... and taking note that the rails asset pipeline doesn't do recursive inclusions for directives and I don't think this is a good idea. It is adding additional complexity to an already complex thing.

**Pull request closed without merging**
